### ISSUE TITLE
How to Open All Bags?

### ISSUE THREAD

**Issue by sadfx** [obble/ladyui#3]
How can I get it to open all bags without having to click the bag at the bottom? I'm not a big fan of the dropdown for the bags or character pages, was this designed for a clicker by any chance?

Does modui work for 2.4.3 by any chance (or would it require much work to make it work)?

**Comment by obble** [comment]
i added a onebag system for myself the other day, which is now uploaded. re-open this ticket if you have any issues with it.

im not planning on pulling modui across or updating it much, this is a just a bare-bones UI system for my own play.
